### ISSUE TITLE
Cannot find module browser-sync

### ISSUE THREAD

**Issue by Ugarz** [brawlins/react-webpack-php-starter#1]
Hello,
This is an intresting project, this is what I was looking for a moment :)
Just to say that you don't have `browser-sync` in your dependencies, and when you `npm install`it you have this error :

```
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/react-php/node_modules/browser-sync-webpack-plugin/index.js:2:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Solution :

```
npm i browser-sync --save
npm start
```

Thanks for this repo' btw 👍

**Comment by emersonreyes** [comment]
Thanks Ugarz for the solution!

**Comment by techednelson** [comment]
Thanks Ugarz for posting this solution, it really worked

**Comment by Klimchenkov** [comment]
Cool!

**Comment by ffreemanjr** [comment]
Thank you for this solution.

**Comment by ArunrajasekarExtendo** [comment]
even after using 
1: npm i browser-sync --save
2: npm start 
it shows me [webpack-dev-server] [HPM] Error occurred while proxying request localhost:50405/api/account to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors) 
can anyone explain
