### ISSUE TITLE
I have to install browser-sync manually.

### ISSUE THREAD

**Issue by viktorstrate** [brawlins/react-webpack-php-starter#3]
When I try to run `npm start`, after installing the packages, it exits with an error, saying that the module `browser-sync`, isn't installed. But everything works fine after installing the package.

I don't know if i'm doing something wrong, or if `browser-sync` should be added to the package.json file

```bash
$ webpack
module.js:471
    throw err;
    ^

Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\robospace\node_modules\browser-sync-webpack-plugin\index.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by kilnamkim** [comment]
@viktorstrate 
You should install browser-sync locally. 

```cmd
npm install --save browser-sync
```

**Comment by viktorstrate** [comment]
I did add id locally, and then everything worked, i just thought it should be a dependency for react-webpack-php-starter?
